# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jakub Ra
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Jakub Ra Photos
baseurl: "/strobo" # the subpath of your site, e.g. /blog
url: "https://lonerscompany.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  schitacci

# Build settings
markdown: kramdown
theme: minima

plugins:
 - jekyll-feed

# styles
sass:
  sass_dir: _sass
  style: compressed

# images and cloudinary
img_url: "https://res.cloudinary.com/dhxmg9p4i/image/upload/"

# excludes
exclude:
  - package.json
  - node_modules
  - gulpfile.js

# collections setings
collections:
  projects:
    output: true

  about:
    output: false


# Exclude from processing. test
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package-lock.json
  - package.json


gems:
  - jekyll-babel
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
